const StateValue = {
    "Adder": "$2.600.000",
    "Albany Escalade": "$3.500.000",
    "Alpha": "$880.000",
    "Annis 350Z": "$2.750.000",
    "Annis GT-R I": "$3.800.000",
    "Annis RX-7 (FD)": "$450.000",
    "Annis RX-8": "$1.300.000",
    "Annis Silvia (S15)": "$900.000",
    "Annis Skyline GT-R (R34)": "$2.500.000",
    "Annis WRX 2004": "$1.300.000",
    "Annis ZR-350": "$900.000",
    "Apocalypse Impaler": "$490.000",
    "Apocalypse Imperator": "$500.000",
    "Apocalypse Issi": "$10.000",
    "Apocalypse Slamvan": "$20.000",
    "Ardent": "$2.000.000",
    "Asbo": "Unknown",
    "Asea": "Unknown",
    "Asterope": "Unknown",
    "Autarch": "Unknown",
    "Annis RX-7 (VF)": "Unknown",
    "Baller": "Unknown",
    "Baller LE LWB": "Unknown",
    "Baller SG": "Unknown",
    "Banshee": "Unknown",
    "Banshee 900R": "Unknown",
    "Beater Emperor": "Unknown",
    "Beater Mariachi Tornado": "Unknown",
    "Beater Surfer": "Unknown",
    "Beater Tornado": "Unknown",
    "Benefactor 600SEL (W140)": "Unknown",
    "Benefactor C63 Coupe (W205)": "Unknown",
    "Benefactor E420 (W210)": "Unknown",
    "Benefactor G63 (G770)": "Unknown",
    "Benefactor GT Black Series": "Unknown",
    "Benefactor GT-63 (S)": "Unknown",
    "Benefactor S63 (W222)": "Unknown",
    "Benefactor Vito (V447)": "Unknown",
    "Benefactor-AMG C63 (W205)": "Unknown",
    "Benefactor-AMG GT": "Unknown",
    "Benefactor-AMG GT 63 (S)": "Unknown",
    "Benefactor-AMG SL65 (R230)": "Unknown",
    "Benefactor-Maybach Pullman": "Unknown",
    "Benefactor-MG VT": "Unknown",
    "Bestia GTS": "Unknown",
    "Bison": "Unknown",
    "Blade": "Unknown",
    "Blista": "Unknown",
    "Blista Kanjo": "Unknown",
    "Bodhi": "Unknown",
    "Bravado Charger 1969": "Unknown",
    "Bravado Charger SRT": "Unknown",
    "Bravado Ram 1500": "Unknown",
    "Bravado Viper 2008": "Unknown",
    "Brawler": "Unknown",
    "Brioso R/A": "Unknown",
    "Buccaneer": "Unknown",
    "Buffalo": "Unknown",
    "Bullet": "Unknown",
    "Burgerfahrzeug Golf GTI Vision": "Unknown",
    "Burgerfahrzeug Tiguan": "Unknown",
    "Calico GTF": "Unknown",
    "Caracara 4x4": "Unknown",
    "Carbonizzare": "Unknown",
    "Casco": "Unknown",
    "Cavalcade": "Unknown",
    "Cheburek": "Unknown",
    "Cheetah": "Unknown",
    "Cheetah Classic": "Unknown",
    "Chino": "Unknown",
    "Clique": "Unknown",
    "Cognoscenti": "Unknown",
    "Cognoscenti 55": "Unknown",
    "Cognoscenti Cabrio": "Unknown",
    "Coil Cybertruck": "Unknown",
    "Coil H9": "Unknown",
    "Coil Model S": "Unknown",
    "Coil Model X": "Unknown",
    "Coil Roadster": "Unknown",
    "Comet": "Unknown",
    "Comet S2": "Unknown",
    "Comet SR": "Unknown",
    "Contender": "Unknown",
    "Coquette": "Unknown",
    "Coquette Blackfin": "Unknown",
    "Coquette Classic": "Unknown",
    "Coquette D10": "Unknown",
    "Cyclone": "Unknown",
    "Cypher": "Unknown",
    "Declasse Camaro 2020": "Unknown",
    "Declasse Corvette C7": "Unknown",
    "Declasse Tahoe": "Unknown",
    "Deveste Eight": "Unknown",
    "Deviant": "Unknown",
    "Dilettante": "Unknown",
    "Dinka NSX 2017": "Unknown",
    "Dinka RT-3000": "Unknown",
    "Dominator": "Unknown",
    "Dominator ASP": "Unknown",
    "Dominator GTT": "Unknown",
    "Dominator GTX": "Unknown",
    "Dominator PiBwasser": "Unknown",
    "Drift Yosemite": "Unknown",
    "Dubsta": "Unknown",
    "Dubsta 6x6": "Unknown",
    "Dubsta SG": "Unknown",
    "Dukes": "Unknown",
    "Elegy Retro Custom": "Unknown",
    "Elegy RH8": "Unknown",
    "Ellie": "Unknown",
    "Emperor": "Unknown",
    "Emperor LX-570": "Unknown",
    "Emperor RCF": "Unknown",
    "Entity XF": "Unknown",
    "Enus Bentayga": "Unknown",
    "Enus Continental GT": "Unknown",
    "Enus Cullinan": "Unknown",
    "Enus Phantom": "Unknown",
    "ETR-1": "Unknown",
    "Euros": "Unknown",
    "Exemplar": "Unknown",
    "Enus Spectre": "Unknown",
    "F620": "Unknown",
    "Faction": "Unknown",
    "Felon": "Unknown",
    "Felon GT": "Unknown",
    "Feltzer": "Unknown",
    "Flash GT": "Unknown",
    "FMJ": "Unknown",
    "FQ 2": "Unknown",
    "Fugitive": "Unknown",
    "Furore GT": "Unknown",
    "Fusilade": "Unknown",
    "Futo": "Unknown",
    "Futo GTX": "Unknown",
    "Future Shock Issi": "Unknown",
    "Gallivanter Defender": "Unknown",
    "Gallivanter Velar": "Unknown",
    "Gauntlet": "Unknown",
    "Gauntlet Classic": "Unknown",
    "Gauntlet Hellfire": "Unknown",
    "Gauntlet Redwood": "Unknown",
    "GB200": "Unknown",
    "Glendale": "Unknown",
    "GP-1": "Unknown",
    "Granger": "Unknown",
    "Grotti Italia (F458)": "Unknown",
    "Grotti Purosangue": "Unknown",
    "Growler": "Unknown",
    "GT 500": "Unknown",
    "Hermes": "Unknown",
    "Hotknife": "Unknown",
    "Huntley S": "Unknown",
    "Imorgon": "Unknown",
    "Impaler": "Unknown",
    "Infernus": "Unknown",
    "Infernus Classic": "Unknown",
    "Ingot": "Unknown",
    "Issi": "Unknown",
    "Itali GTB": "Unknown",
    "Itali GTB Custom": "Unknown",
    "Itali GTO": "Unknown",
    "Jackal": "Unknown",
    "JB 700": "Unknown",
    "Jester": "Unknown",
    "Jester (Racecar)": "Unknown",
    "Jester Classic": "Unknown",
    "Jester RR": "Unknown",
    "Journey": "Unknown",
    "Jugular": "Unknown",
    "Kamacho": "Unknown",
    "Karin Land Cruiser 200": "Unknown",
    "Karin Mark 2": "Unknown",
    "Karin Rav4 2021": "Unknown",
    "Karin Supra A80": "Unknown",
    "Karin Tundra 2021": "Unknown",
    "Khamelion": "Unknown",
    "Komoda": "Unknown",
    "Krieger": "Unknown",
    "Kuruma": "Unknown",
    "Lampadati Guilia GTA": "Unknown",
    "Landstalker": "Unknown",
    "Lynx": "Unknown",
    "Mamba": "Unknown",
    "Mammoth Hum EV": "Unknown",
    "Massacro": "Unknown",
    "Monroe": "Unknown",
    "Moonbeam": "Unknown",
    "Nebula Turbo": "Unknown",
    "Neon": "Unknown",
    "Nero": "Unknown",
    "Nero Custom": "Unknown",
    "Nightshade": "Unknown",
    "Novak": "Unknown",
    "Obey A6": "Unknown",
    "Obey A8": "Unknown",
    "Obey Q60": "Unknown",
    "Obey Q8": "Unknown",
    "Obey R8": "Unknown",
    "Obey RS6": "Unknown",
    "Obey RS7": "Unknown",
    "Obey S8 (D4)": "Unknown",
    "Ocelot DBS GT Zagato": "Unknown",
    "Ocelot Eletre": "Unknown",
    "Ocelot F-Type R": "Unknown",
    "Ocelot V12 Speedster": "Unknown",
    "Ocelot Vanquish Zagato SB": "Unknown",
    "Ocelot Victor": "Unknown",
    "Ocelot XE SV Project 8": "Unknown",
    "Octavia RS": "Unknown",
    "Oracle": "Unknown",
    "Osiris": "Unknown",
    "Panto": "Unknown",
    "Paragon R": "Unknown",
    "Pariah": "Unknown",
    "Patriot": "Unknown",
    "Patriot Stretch": "Unknown",
    "Pegassi Huayra BC": "Unknown",
    "Pegassi Performante (LP640)": "Unknown",
    "Penetrator": "Unknown",
    "Penumbra": "Unknown",
    "Pfister 911": "Unknown",
    "Pfister 918 Spyder": "Unknown",
    "Pfister Panamera": "Unknown",
    "Pfister Taycan": "Unknown",
    "Pheonix": "Unknown",
    "Picador": "Unknown",
    "Prairie": "Unknown",
    "Premier": "Unknown",
    "Previon": "Unknown",
    "Progen P1": "Unknown",
    "Pfister 811": "Unknown",
    "Raiden": "Unknown",
    "Rancher XL": "Unknown",
    "Rapid GT": "Unknown",
    "Raptor": "Unknown",
    "Rat-Loader": "Unknown",
    "Rat-Truck": "Unknown",
    "RE-7B": "Unknown",
    "Reaper": "Unknown",
    "Rebel": "Unknown",
    "Rebla GTS": "Unknown",
    "Regina": "Unknown",
    "Remus": "Unknown",
    "Revolter": "Unknown",
    "Rhapsody": "Unknown",
    "Riata": "Unknown",
    "Rocoto": "Unknown",
    "Ruiner": "Unknown",
    "Rumpo": "Unknown",
    "Ruston": "Unknown",
    "Rusty Rebel": "Unknown",
    "Sabre Turbo": "Unknown",
    "Sandking SWB": "Unknown",
    "Sandking XL": "Unknown",
    "SC-1": "Unknown",
    "Schafter": "Unknown",
    "Schafter LWB": "Unknown",
    "Schafter LWB (Armored)": "Unknown",
    "Schafter V12": "Unknown",
    "Schlagen GT": "Unknown",
    "Schwarzer": "Unknown",
    "Seminole": "Unknown",
    "Sentinel Classic": "Unknown",
    "Sentinel XS": "Unknown",
    "Serrano": "Unknown",
    "Seven-70": "Unknown",
    "Shelby GT500": "Unknown",
    "Slamvan": "Unknown",
    "Slamvan Custom": "Unknown",
    "Specter": "Unknown",
    "Stafford": "Unknown",
    "StafVapid": "Unknown",
    "Stalion": "Unknown",
    "Stinger": "Unknown",
    "Stinger GT": "Unknown",
    "Stirling GT": "Unknown",
    "Streiter": "Unknown",
    "Stretch": "Unknown",
    "Sultan": "Unknown",
    "Sultan Classic": "Unknown",
    "Sultan RS": "Unknown",
    "Sultan RS Classic": "Unknown",
    "Super Diamond": "Unknown",
    "Surano": "Unknown",
    "Surge": "Unknown",
    "Swinger": "Unknown",
    "T-20": "Unknown",
    "Tailgater": "Unknown",
    "Tailgater S": "Unknown",
    "Taipan": "Unknown",
    "Tampa": "Unknown",
    "Tempesta": "Unknown",
    "Tezeract": "Unknown",
    "Thrax": "Unknown",
    "Tigon": "Unknown",
    "Torero": "Unknown",
    "Toros": "Unknown",
    "Tropos Rallye": "Unknown",
    "Truffade Chiron": "Unknown",
    "Tulip": "Unknown",
    "Turismo Classic": "Unknown",
    "Turismo R": "Unknown",
    "Tyrant": "Unknown",
    "Tyrus": "Unknown",
    "Ubermacht 760 (LI)": "Unknown",
    "Ubermacht I8": "Unknown",
    "Ubermacht M3 (E46)": "Unknown",
    "Ubermacht M3 (G80)": "Unknown",
    "Ubermacht M3 CS": "Unknown",
    "Ubermacht M4 (G82)": "Unknown",
    "Ubermacht M4 (GTS)": "Unknown",
    "Ubermacht M5 (CS)": "Unknown",
    "Ubermacht M5 (E34)": "Unknown",
    "Ubermacht M5 (E60)": "Unknown",
    "Ubermacht M5 (F90)": "Unknown",
    "Ubermacht M8 (F91)": "Unknown",
    "Ubermacht X5 (E70)": "Unknown",
    "Ubermacht X5 (G05)": "Unknown",
    "Ubermacht X5-M (F95)": "Unknown",
    "Ubermacht X6-M (E71)": "Unknown",
    "Ubermacht X6-M 2021": "Unknown",
    "Ubermacht X7 (G07)": "Unknown",
    "V-STR": "Unknown",
    "Vacca": "Unknown",
    "Vagner": "Unknown",
    "Vamos": "Unknown",
    "Vapid Mustang GT500": "Unknown",
    "Vapid Raptor (F150)": "Unknown",
    "Vectre": "Unknown",
    "Velierer": "Unknown",
    "Vigero": "Unknown",
    "Virgo": "Unknown",
    "Virgo Classic": "Unknown",
    "Visione": "Unknown",
    "Voltic": "Unknown",
    "Voodoo": "Unknown",
    "Voodoo Custom": "Unknown",
    "Warrener": "Unknown",
    "Warrener HKR": "Unknown",
    "Washington": "Unknown",
    "Windsor": "Unknown",
    "Windsor Drop": "Unknown",
    "X80 Proto": "Unknown",
    "XA-21": "Unknown",
    "XLS": "Unknown",
    "XLS (Armored)": "Unknown",
    "Yosemite": "Unknown",
    "Yosemite Rancher": "Unknown",
    "Z-Type": "Unknown",
    "Zentorno": "Unknown",
    "Zion": "Unknown",
    "Zion Cabrio": "Unknown",
    "Zion Classic": "Unknown",
    "Zorrusso": "Unknown",
    "9F": "Unknown",
    "9F Cabrio": "Unknown",
    "Dinghy": "Unknown",
    "Dinghy (2-Seater)": "Unknown",
    "Dinghy (Yacht)": "Unknown",
    "Jetmax": "Unknown",
    "Marquis": "Unknown",
    "SeaShark": "Unknown",
    "Speeder": "Unknown",
    "Squalo": "Unknown",
    "Suntrap": "Unknown",
    "Toro": "Unknown",
    "Tropic": "Unknown",
    "Alpha-Z1": "Unknown",
    "Cuban 800": "Unknown",
    "Dodo": "Unknown",
    "Duster": "Unknown",
    "Howard NX-25": "Unknown",
    "Luxor": "Unknown",
    "Luxor Deluxe": "Unknown",
    "Malard": "Unknown",
    "Mammatus": "Unknown",
    "Microlight": "Unknown",
    "Nimbus": "Unknown",
    "P-45 Nokota": "Unknown",
    "V-65 Molotok": "Unknown",
    "Velum": "Unknown",
    "Buzzard": "Unknown",
    "Frogger": "Unknown",
    "Maverick": "Unknown",
    "Sparrow": "Unknown",
    "SuperVolito Carbon": "Unknown",
    "Swift Deluxe": "Unknown",
    "Volatus": "Unknown",
    "Akuma": "Unknown",
    "Apocalypse Deathbike": "Unknown",
    "Avarus": "Unknown",
    "Bagger": "Unknown",
    "Bati 801": "Unknown",
    "Bati 801RR": "Unknown",
    "BF-400": "Unknown",
    "Blazer": "Unknown",
    "Blazer Lifeguard": "Unknown",
    "BMX": "Unknown",
    "Carbon RS": "Unknown",
    "Chimera": "Unknown",
    "Cliffhanger": "Unknown",
    "Cruiser": "Unknown",
    "Daemon": "Unknown",
    "Defiler": "Unknown",
    "Diabolus": "Unknown",
    "Diabolus Custom": "Unknown",
    "Double-T": "Unknown",
    "Enduro": "Unknown",
    "Esskey": "Unknown",
    "Faggio": "Unknown",
    "FCR 1000": "Unknown",
    "FCR 1000 Custom": "Unknown",
    "Future Shock Deathbike": "Unknown",
    "Gargoyle": "Unknown",
    "Hakuchou": "Unknown",
    "Hakuchou Drag": "Unknown",
    "Hexer": "Unknown",
    "Innovation": "Unknown",
    "Lectro": "Unknown",
    "Manchez": "Unknown",
    "Nemesis": "Unknown",
    "Nightblade": "Unknown",
    "PCJ-600": "Unknown",
    "Rat Bike": "Unknown",
    "Ruffian": "Unknown",
    "Sanchez": "Unknown",
    "Sanctus": "Unknown",
    "Shotaro": "Unknown",
    "Sovereign": "Unknown",
    "Street Blazer": "Unknown",
    "Thrust": "Unknown",
    "Tri-Cycles Race Bike": "Unknown",
    "Vader": "Unknown",
    "Vindicator": "Unknown",
    "Vortex": "Unknown",
    "Whippet Race Bike": "Unknown",
    "Wolfsbane": "Unknown",
    "Zombie Chopper": "Unknown",
}

function fetchStateValue() {
    const carName = document.getElementById("car-name").value;
    const result = document.getElementById("car_state_value");

    const price = StateValue[carName];

    if (!price) {
        result.textContent = "Unknown";
        return;
    }

    result.textContent = formatToShortAmount(price);
}

function formatToShortAmount(amountString) {
    // remove $ sign and dots
    const clean = amountString.replace(/\$/g, "").replace(/\./g, "");
    const num = parseInt(clean);

    if (!num) return "Unknown";

    if (num >= 1_000_000_000) {
        // Billion
        return "Negotiable";
    }

    if (num >= 1_000_000) {
        // Million
        return "$" + (num / 1_000_000).toFixed(1) + " Million";
    }

    if (num >= 1_000) {
        // return as it is
        return amountString;
    }

    return num.toString(); // small values
}
